hyper_params:
  dim_output: 3
  dim_ffnn: 1024
  num_blocks: 2
  num_heads: 12
  depth: 32
  batch_size: 128
  learning_rate: 0.0003
  dropout_rate: 0.1


branches:
  track_branches: ['track_pt', 'track_eta', 'track_phi',
    'track_deta', 'track_dphi',
    'track_x', 'track_ptrel', 'track_pzrel',
    'track_d0', 'track_dz',
    'track_charge']
  tower_branches: ['tower_E', 'tower_Eem', 'tower_Ehad']
  lepton_branches: ['lep_pt', 'lep_eta', 'lep_phi', 'lep_mass', 'lep_charge', 'lep_isMuon']
  met_branches: ['met', 'met_phi']
  target_branch: 'jet_parton_match_detail'
  reco_branches: ['weight']


loader_args:
  pin_memory: True
  shuffle: True


n_epoch: 300
